import type { Metadata } from 'next'
import { locales, defaultLocale, type Locale } from '@/i18n/routing'

/**
 * SEO helpers (T7).
 *
 * Single source of truth for site-level metadata: the canonical origin, the
 * locale → URL mapping (D-locale `as-needed`: ES is the bare apex, EN lives at
 * `/en`), and a `buildMetadata` factory that every route's `generateMetadata`
 * uses so canonical + hreflang `alternates` are produced ONE way, never by hand.
 *
 * Hard rules honored: vocabulary is "perfil" / "verifiable" (the public copy that
 * feeds titles/descriptions lives in the message files and is already paper-only,
 * never onchain/crypto). This module only wires structure.
 */

/**
 * Canonical site origin. Comes from `NEXT_PUBLIC_SITE_URL` (set in `.env`);
 * falls back to the production apex so `next build` / sitemap / OG never emit a
 * relative or `localhost` canonical by accident. No trailing slash.
 */
export const SITE_URL = (
  process.env.NEXT_PUBLIC_SITE_URL ?? 'https://frutero.club'
).replace(/\/$/, '')

export const SITE_NAME = 'Frutero Club'

/**
 * Canonical production origin. ONLY this host is indexable — every other deploy
 * (dev.frutero.club, Vercel previews, localhost) is treated as staging and gets
 * noindex + robots disallow-all (see `INDEXABLE`), so a public preview never
 * competes with or pre-empts the real launch in search.
 */
export const PRODUCTION_URL = 'https://frutero.club'

/**
 * Whether this deploy should be indexed. True only when pointed at the
 * production apex via `NEXT_PUBLIC_SITE_URL`. Staging stays fully reachable for
 * the team but invisible to search engines. Set `NEXT_PUBLIC_SITE_URL` per
 * environment on Vercel (dev → https://dev.frutero.club, prod → the apex) so
 * canonical/OG/sitemap also resolve to the host the page is actually served on.
 */
export const INDEXABLE = SITE_URL === PRODUCTION_URL

/**
 * The single Open Graph / Twitter card image. Generated by the edge route
 * `app/opengraph-image.tsx` (served at `/opengraph-image`). Referenced as an
 * ABSOLUTE URL so social scrapers always resolve it — the file-convention
 * auto-injection does not cascade reliably from the root segment down to the
 * `[locale]` routes (the metadataBase that resolves it lives in the locale
 * layout, two segments below the image file), which left every page with no
 * `og:image`. Wiring it here is unambiguous and verifiable.
 */
export const OG_IMAGE = {
  url: `${SITE_URL}/opengraph-image`,
  width: 1200,
  height: 630,
  alt: `${SITE_NAME} — Aceleradora de Talento`,
} as const

/** BCP-47 tags for the two locales (used in OG `locale` + hreflang). */
export const localeToBcp47: Record<Locale, string> = {
  es: 'es_MX',
  en: 'en_US',
}

/**
 * Map a route's locale + in-app pathname to its absolute, canonical URL.
 * `path` is the locale-less route (e.g. `'/'`, `'/enterprise'`). ES is served at
 * the bare apex (no `/es` prefix); EN is prefixed with `/en`.
 */
export function localizedUrl(locale: Locale, path = '/'): string {
  const clean = path === '/' ? '' : path.replace(/\/$/, '')
  if (locale === defaultLocale) {
    return `${SITE_URL}${clean || '/'}`
  }
  return `${SITE_URL}/${locale}${clean}`
}

/**
 * Build the `alternates` block (self-canonical + every-locale hreflang +
 * `x-default` → ES) for a given route path. `/es/...` is never emitted — the
 * default locale is always the bare apex, matching the proxy canonicalizer.
 */
export function buildAlternates(locale: Locale, path = '/'): Metadata['alternates'] {
  const languages: Record<string, string> = {}
  for (const l of locales) {
    languages[localeToBcp47[l].replace('_', '-')] = localizedUrl(l, path)
  }
  // x-default points at the primary (ES) market per D-locale.
  languages['x-default'] = localizedUrl(defaultLocale, path)
  return {
    canonical: localizedUrl(locale, path),
    languages,
  }
}

/**
 * Official community profiles — the `sameAs` edges that let Google reconcile the
 * site with Frutero Club's social identities (entity recognition / brand SERP).
 * Mirror of the links in `components/marketing/SiteFooter.tsx`.
 */
export const SOCIAL_LINKS = [
  'https://warpcast.com/~/channel/fruteroclub',
  'https://twitter.com/fruteroclub',
  'https://t.me/fruteroclub',
  'https://github.com/fruteroclub',
] as const

/**
 * Site-wide structured data (JSON-LD) as a single schema.org `@graph`:
 *  - `Organization` — the entity (name, logo, social `sameAs`) so search engines
 *    recognize Frutero Club as a brand, not just a page.
 *  - `WebSite` — the publication itself, tied to the org as `publisher`.
 *
 * `description` is the locale's meta description (kept in sync with the page);
 * the absolute `logo`/`url` resolve against the canonical origin (JSON-LD is raw
 * markup — `metadataBase` does NOT apply, so URLs must be absolute here).
 */
export function siteJsonLd(locale: Locale, description: string) {
  const orgId = `${SITE_URL}/#organization`
  return {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Organization',
        '@id': orgId,
        name: SITE_NAME,
        url: SITE_URL,
        logo: `${SITE_URL}/logo.png`,
        description,
        sameAs: [...SOCIAL_LINKS],
      },
      {
        '@type': 'WebSite',
        '@id': `${SITE_URL}/#website`,
        name: SITE_NAME,
        url: SITE_URL,
        description,
        inLanguage: localeToBcp47[locale].replace('_', '-'),
        publisher: { '@id': orgId },
      },
    ],
  }
}

export interface BuildMetadataArgs {
  locale: Locale
  /** Locale-less route path, e.g. `'/'` or `'/enterprise'`. */
  path?: string
  title: string
  description: string
  /** Set false for non-indexable surfaces (e.g. authed app). Defaults true. */
  index?: boolean
  /**
   * Per-route OG/Twitter image override. Defaults to the single-path site card
   * (`OG_IMAGE`). Pass an absolute URL for routes with their own card — e.g.
   * `/noticias/[slug]/opengraph-image` (DEC-9: the file convention does NOT
   * cascade through `[locale]`, so the article route wires its card explicitly).
   */
  image?: { url: string; width?: number; height?: number; alt?: string }
}

/**
 * The one metadata factory. Produces title/description + canonical + hreflang +
 * Open Graph + Twitter card for a marketing route. The single-path
 * `opengraph-image.tsx` is picked up automatically by Next from the file
 * convention — we set `openGraph`/`twitter` text fields here and let the
 * convention supply the image, so there is exactly one OG image path.
 */
export function buildMetadata({
  locale,
  path = '/',
  title,
  description,
  index = true,
  image,
}: BuildMetadataArgs): Metadata {
  const ogImage = image
    ? { url: image.url, width: image.width ?? 1200, height: image.height ?? 630, alt: image.alt }
    : OG_IMAGE
  return {
    // `absolute` so the route's own title is used verbatim (these titles already
    // contain the brand) and is NOT wrapped by the layout's `%s · Frutero Club`
    // template.
    title: { absolute: title },
    description,
    alternates: buildAlternates(locale, path),
    openGraph: {
      type: 'website',
      siteName: SITE_NAME,
      title,
      description,
      url: localizedUrl(locale, path),
      locale: localeToBcp47[locale],
      images: [ogImage],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [ogImage.url],
    },
    // Per-page opt-out (e.g. authed surfaces) OR a non-production deploy both
    // force noindex; only an indexable page on the production host stays open.
    robots:
      index && INDEXABLE
        ? undefined
        : { index: false, follow: false },
  }
}

export interface ArticleJsonLdArgs {
  title: string
  dek?: string
  /** ISO date 'YYYY-MM-DD'. */
  date: string
  author: { name: string; handle: string }
  /** Absolute canonical URL of the article. */
  url: string
  /** Absolute URL of the article's OG image. */
  image: string
}

/**
 * `NewsArticle` JSON-LD for an article page (T5). Tied to the site `Organization`
 * as `publisher` via its `@id` (the org node is emitted site-wide by
 * {@link siteJsonLd} in the locale layout, so this references it rather than
 * re-declaring it). Rendered on `/noticias/[slug]` alongside the page.
 */
export function articleJsonLd(locale: Locale, a: ArticleJsonLdArgs) {
  return {
    '@context': 'https://schema.org',
    '@type': 'NewsArticle',
    headline: a.title,
    description: a.dek ?? '',
    inLanguage: localeToBcp47[locale].replace('_', '-'),
    datePublished: a.date,
    dateModified: a.date,
    image: [a.image],
    url: a.url,
    mainEntityOfPage: a.url,
    author: { '@type': 'Person', name: a.author.name, identifier: `@${a.author.handle}` },
    publisher: { '@id': `${SITE_URL}/#organization` },
  }
}
